from room import Room
from player import Player
from world import World

import random
from ast import literal_eval

# Load world
world = World()


# You may uncomment the smaller graphs for development and testing purposes.
# map_file = "maps/test_line.txt"
# map_file = "maps/test_cross.txt"
# map_file = "maps/test_loop.txt"
# map_file = "maps/test_loop_fork.txt"
map_file = "maps/main_maze.txt"

# Loads the map into a dictionary
room_graph = literal_eval(open(map_file, "r").read())
world.load_graph(room_graph)

# Print an ASCII map
world.print_rooms()

player = Player(world.starting_room)

# Fill this out with directions to walk
# traversal_path = ['n', 'n']
# sequential travel directions
traversal_path = []
# set of all visited rooms
visited = set()
# map of maze up to current point: adjacency list - used to find the shortest path to an unexplored room with BFS
adj_list = {}
# set of rooms that are 'known-but-unvisited' - used to as lookup table to tell BFS where to stop
unvis_rooms = set()

# Using 'adj_list', find shortest path to an unexplored room - returns a list of rooms in order that they should be traversed


def find_path_to_unexplored(starting_vert=0, des_set=1):
    queue = [[starting_vert]]
    seen = {}
    seen[starting_vert] = True
    while len(queue) > 0:
        current_path = queue.pop(0)
        if current_path[-1] in des_set:
            return current_path
        for i in adj_list[current_path[-1]]:
            if i not in seen:
                seen[i] = True
                new_path = current_path + [i]
                queue.append(new_path)


# Use shortest path generated by 'find_path_to_unexplored' to navigate to nearest unexplored room
def navigate_to(path_list=[]):
    # remove room from the 'known-but-unvisited' list
    if player.current_room.id == path_list[-1]:
        unvis_rooms.remove(path_list[-1])
    while player.current_room.id != path_list[-1]:
        c_room = player.current_room
        a_exits = c_room.get_exits()
        path_list.pop(0)
        for i in a_exits:
            a_room = c_room.get_room_in_direction(i).id
            if a_room == path_list[0]:
                traversal_path.append(i)
                player.travel(i)


while len(visited) < len(room_graph):
    current_room = player.current_room
    exits = current_room.get_exits()
    # If current room has not been previously visited
    if current_room.id not in visited:
        visited.add(current_room.id)
        adj_list[current_room.id] = []
        for i in exits:
            adj_room_id = current_room.get_room_in_direction(i).id
            adj_list[current_room.id].append(adj_room_id)
            if adj_room_id not in visited and adj_room_id not in unvis_rooms:
                unvis_rooms.add(adj_room_id)

    # make list of unexplored exits by checking if adjacent rooms are on the visited list
    unexplored_exits = []
    for exit in exits:
        adj_room_id = current_room.get_room_in_direction(exit).id
        if adj_room_id not in visited:
            unexplored_exits.append((adj_room_id, exit))

    # if unexplored exit exists, choose one at random and travel to it
    if len(unexplored_exits) > 0:
        travel_index = random.randint(0, len(unexplored_exits)-1)
        next_room_id = unexplored_exits[travel_index][0]
        next_room_dir = unexplored_exits[travel_index][1]
        # add to the traversal path
        traversal_path.append(next_room_dir)
        # travel to next room
        player.travel(next_room_dir)
        # remove from the unvisited list and set
        unvis_rooms.remove(next_room_id)

    # if no unexplored exits start the breadth-first search to find shortest path to unexplored room, then navigate to that room
    elif len(unexplored_exits) == 0:
        shortest_path = find_path_to_unexplored(
            player.current_room.id, unvis_rooms)
        navigate_to(shortest_path)

# TRAVERSAL TEST - DO NOT MODIFY
visited_rooms = set()
player.current_room = world.starting_room
visited_rooms.add(player.current_room)

for move in traversal_path:
    player.travel(move)
    visited_rooms.add(player.current_room)

if len(visited_rooms) == len(room_graph):
    print(
        f"TESTS PASSED: {len(traversal_path)} moves, {len(visited_rooms)} rooms visited")
else:
    print("TESTS FAILED: INCOMPLETE TRAVERSAL")
    print(f"{len(room_graph) - len(visited_rooms)} unvisited rooms")


#######
# UNCOMMENT TO WALK AROUND
#######
# player.current_room.print_room_description(player)
# while True:
#     cmds = input("-> ").lower().split(" ")
#     if cmds[0] in ["n", "s", "e", "w"]:
#         player.travel(cmds[0], True)
#     elif cmds[0] == "q":
#         break
#     else:
#         print("I did not understand that command.")
